language: java
notifications:
  slack:
    secure: R9rabV1tVHFE6+3EyNeM5FxPtcHA5kJG+ta1NsbY8jhkoTB/JC+/Cm7TAFZrIbqYJrbKgaAnimDyhb8vnyTYT4zXrIZyulOaKHhf75rueFG0zcg3I1N0DUCvgTmgnVhleFnlRLfNlWpULjHLgNn379Rvn3/lFEQkx8hpLrZd6i+zsjFhePIRLLkxmrCYoNjeQ7yjtBOX6aJU2PfhbBnRafC36m4FuDJWtGO0sJRu9soN5fJCuSleqz9/KliYR4jtjO6bWqOrXvFWnLn8wg1dIjQKpp4+qgkd2eOPd6dWHl2y93nT1QXYW7TOLjLGd6CwC/lQAVufSv9yz4fze5YMLIKnAxWcCfaPY7XQBMliKKsTb3JtZ2n2HAPK1+GOzoMZE3StUs+ID9d2+7RJaXDQfOfHjfUteya8Cz88H6KEZ5wML815S6oDPDKxIMjUq+R6W3wi0lbkO14F5jo86nu3SxwAOSREemdRzpBIeXJtCLAJhXdE1n9EqUH03NVehNMKuQtwlQEoMw3MIzWkg4JjP7XGtqWtX1X72Qc0dIDcgWNJwrVEIWk4hDzFQU862tIfLRUWEveJledNJ44AAq5O6K6MRG3DQd3ikR/uWD4aCDgQER+9DOwvqNPOvrMbAm346eQki7X13Co0yCyhL01Q6DasHpnOkG4Cg1osO4iz4S0=
deploy:
  provider: releases
  api_key:
    secure: EZI+C19zW86x9S0UVX/FvHa3Olep+UEqjWZKnTPG5s6X4iZrX8XbXdcvgwjsPXzSz8n2bvBhhSLTNN3WH/K5G1wKIZjFai/9olodGibaum3TKYDuFZKbNt3hLxF76kbbc+NPomJ08vLCZFxqMEIk+El1GSd5Qz6xOo9+Lh3ZmFj/sKM3quGM52C4H6UiBRk0I8C1jNGcii260xyjwYhg/QxrPjegfaA1Bwim7wW3JpgvaOWybuqz82le7rXtAST4vkDd39dpGaVyQrQelngPg3UU6Bo+Zey3JnKH1dKRz2ReOyeV1NnC5NdZCdKguIYSohu+5zCB4c7SG9WJmT0Wi8d1Ct1OXDQCQUsUADQ3h90JaCEDfnr4+RHX5xpUpdbJPd/4c8CkQQdgGz7Xj2zCXlwAmZ5QcyJDeJfqD7k1sjXuz5qLJqaOiofZMEVRc1tuB5QvfkUHhKMhJNcGHtLLmIxgD4+5pwRs5vNT5TUjb+s79YlDYPNzamYrRGaRv8ZJzO3/GPEQ+dyhv/a+61Q7smIhGZZvQdFNc9NberstGG26l0/6fCKSuSLXHPJGWanw6x2h4ZnrWDdXIaI537/TkGfHTdst8LCdJbFLFnWtJURuqiLtiI0jPmTn4gO5tbmrSnWYhMSEWom/DBmhKTmk8Es0gZos3aNpkGw6iAVcXBM=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-variable-setter-plugin
